{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.751.0 (24.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Fact_Sales\",\"Clean_Data_Function\",\"Dim_Customer\",\"StartDate\",\"EndDate\",\"DimDate\",\"_Measure\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Clean_Data_Function",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(DataSheet as table) =>",
          "let",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(DataSheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Invoice\", type any}, {\"StockCode\", type any}, {\"Description\", type text}, {\"Quantity\", Int64.Type}, {\"InvoiceDate\", type datetime}, {\"Price\", type number}, {\"Customer ID\", Int64.Type}, {\"Country\", type text}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Customer ID] <> null and [Customer ID] <> \"\")),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"StockCode\", \"Description\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Invoice\", type text}}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type1\", each not Text.StartsWith([Invoice], \"C\")),",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filtered Rows1\", each [Price] > 0),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Filtered Rows2\",{\"Invoice\", \"InvoiceDate\", \"Customer ID\", \"Country\", \"Quantity\", \"Price\"})",
          "in",
          "    #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "da2c3d4c-650d-41d5-8e7d-725fab63a2e4"
      },
      {
        "name": "StartDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2009, 12, 1)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "067827fe-59df-44b7-b82a-39addf8f231d"
      },
      {
        "name": "EndDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2011, 12, 1)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "b20e5a7e-7f49-484d-97e3-6afcccabd114"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_10403d2c-a23e-4554-ae70-bb055c739657",
        "fromColumn": "Customer ID",
        "fromTable": "Fact_Sales",
        "toColumn": "Customer ID",
        "toTable": "Dim_Customer"
      },
      {
        "name": "5e2ae74c-a7d5-e821-21a2-d8fc9be37f90",
        "fromColumn": "InvoiceDate",
        "fromTable": "Fact_Sales",
        "toColumn": "Date",
        "toTable": "DimDate"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Fact_Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Invoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86577d39-6b6d-4331-857e-c81b137de7a6",
            "sourceColumn": "Invoice",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80224408-7b3b-4b44-80a4-51b7eca4a341",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "InvoiceDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "1c63196d-effd-4062-b786-662da7799c33",
            "sourceColumn": "InvoiceDate",
            "summarizeBy": "none"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "dee25a75-d43b-4f08-bbc1-a4214f6262d5",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "137fae89-9733-4e05-9126-371237d630a2",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "309c9356-f66d-42b2-bd2b-3e5d0c0a1467",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff873f9d-0b8c-4c39-b3b3-1180389eb483",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month Since First Transation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "    DATEDIFF(",
              "        RELATED(Dim_Customer[First_transation_month]),",
              "        RELATED(DimDate[Date]),",
              "        MONTH",
              "    )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "24c6335c-9b6c-4767-b584-58c2c355c0e8",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "cf195353-8c47-48ce-9e85-820478ce5ede",
        "partitions": [
          {
            "name": "Fact_Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Chohort Analysis\\online_retail_II.xlsx\"), null, true),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Kind] = \"Sheet\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Item\", \"Kind\", \"Hidden\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Columns\", \"Clean_Data\", each Clean_Data_Function([Data])),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Invoked Custom Function\",{\"Data\"}),",
                "    #\"Expanded Clean_Data\" = Table.ExpandTableColumn(#\"Removed Columns1\", \"Clean_Data\", {\"Invoice\", \"InvoiceDate\", \"Customer ID\", \"Country\", \"Quantity\", \"Price\"}, {\"Invoice\", \"InvoiceDate\", \"Customer ID\", \"Country\", \"Quantity\", \"Price\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Clean_Data\",{{\"InvoiceDate\", type date}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type\", each true),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows1\",{{\"Quantity\", Int64.Type}, {\"Price\", Currency.Type}, {\"Customer ID\", Int64.Type}, {\"Invoice\", type text}}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Changed Type1\", each true)",
                "in",
                "    #\"Filtered Rows2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fa86e4ac-7b92-4a05-9349-05e5aefdfe28",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "First_transation_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "846bfa7d-a4e6-4bf2-85ad-fed120b4f346",
            "sourceColumn": "First_transation_month",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0c0424eb-3cd8-493a-9b5a-f0f8063cf424",
        "partitions": [
          {
            "name": "Dim_Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Fact_Sales,",
                "    #\"Grouped Rows\" = Table.Group(Source, {\"Customer ID\"}, {{\"First_transation_month\", each List.Min([InvoiceDate]), type nullable date}}),",
                "    #\"Calculated Start of Month\" = Table.TransformColumns(#\"Grouped Rows\",{{\"First_transation_month\", Date.StartOfMonth, type date}})",
                "in",
                "    #\"Calculated Start of Month\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "15c03722-02a5-4377-ad9b-315d45bd918f",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "lineageTag": "fcdecbb5-4cfd-487b-bf3f-b2bd49eae75d",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9c4200b0-3e2e-4451-b8f0-a4b93fac6d60",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = {Number.From(StartDate)..Number.From(EndDate)},",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Converted to Table\",{{\"Column1\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Date\"}}),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Renamed Columns\", \"Start of Month\", each Date.StartOfMonth([Date]), type date)",
                "in",
                "    #\"Inserted Start of Month\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "841983c5-1ba6-4120-baf5-473c445cb668",
        "measures": [
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Regular Measure",
            "expression": "SUMX(Fact_Sales, Fact_Sales[Quantity]*Fact_Sales[Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "8e3bb74a-42c5-4467-85ea-0ca96c4289a7"
          },
          {
            "name": "Total Orders",
            "displayFolder": "Regular Measure",
            "expression": "DISTINCTCOUNT(Fact_Sales[Invoice])",
            "formatString": "0",
            "lineageTag": "2208aefe-bc4c-4c51-9e1d-bdd54d7002e3"
          },
          {
            "name": "Total Unit Sold",
            "displayFolder": "Regular Measure",
            "expression": "SUM(Fact_Sales[Quantity])",
            "formatString": "0",
            "lineageTag": "c9d02731-3e2a-4b6e-b772-1576e6f736de"
          },
          {
            "name": "Total Customer",
            "displayFolder": "Regular Measure",
            "expression": "COUNTROWS(Dim_Customer)",
            "formatString": "0",
            "lineageTag": "bdfb47a3-89ed-4372-b1a7-2830458ef6f0"
          },
          {
            "name": "Average Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Regular Measure",
            "expression": "DIVIDE([Total Revenue], [Total Customer])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "8f956741-43d7-43e5-8ded-97aac5a146a1"
          },
          {
            "name": "Average Order Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Regular Measure",
            "expression": "DIVIDE([Total Revenue], [Total Orders])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "57221760-81be-46be-88d8-e9bad8b321dd"
          },
          {
            "name": "PM Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Regular Measure",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATEADD(DimDate[Date], -1, MONTH)",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ac9dd75a-18ad-411e-b489-69e178f763f5"
          },
          {
            "name": "PM Order",
            "displayFolder": "Regular Measure",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    DATEADD(DimDate[Date], -1, MONTH)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "64647cca-e5f3-400a-bf69-070f7ab6dbd2"
          },
          {
            "name": "Active Customer",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "COUNTROWS(VALUES(Fact_Sales[Customer ID]))"
            ],
            "formatString": "0",
            "lineageTag": "8f1e396d-eb36-431e-8bbb-17407e8affc1"
          },
          {
            "name": "New Customer",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "CALCULATE(",
              "    [Active Customer],",
              "    Fact_Sales[Month Since First Transation]=0)"
            ],
            "formatString": "0",
            "lineageTag": "8e4e5f93-55cc-4c14-a3ca-b3b8582a1e17"
          },
          {
            "name": "Cohort Performance",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "",
              "VAR _minDate = MIN(DimDate[Start of Month])",
              "",
              "VAR _maxDate = MAX(DimDate[Start of Month])",
              "",
              "RETURN",
              "    CALCULATE(",
              "        [Active Customer],",
              "        REMOVEFILTERS(DimDate[Start of Month]),",
              "        RELATEDTABLE(Dim_Customer),",
              "        Dim_Customer[First_transation_month]>= _minDate",
              "            && Dim_Customer[First_transation_month]<= _maxDate",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "bcf8df61-8e0a-46db-83dc-97a97cfcf7fb"
          },
          {
            "name": "Retaind Customers",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "VAR _ThisMonth=VALUES(Fact_Sales[Customer ID])",
              "VAR _LastMonth = CALCULATETABLE(",
              "    VALUES(Fact_Sales[Customer ID]),",
              "    PREVIOUSMONTH(DimDate[Start of Month])",
              ")",
              "VAR _RetaindCustomer = ",
              "    INTERSECT(_ThisMonth, _LastMonth)",
              "RETURN",
              "COUNTROWS(_RetaindCustomer)"
            ],
            "formatString": "0",
            "lineageTag": "9af8baa1-fc0a-46c4-9a28-3636042495a7"
          },
          {
            "name": "Retaintion Rate",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "DIVIDE([Cohort Performance], [New Customer])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dc4c3b31-190e-475c-b5ae-e799e901a826"
          },
          {
            "name": "Churned Customer",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              " SWITCH(",
              "    TRUE(),",
              "    ISBLANK([Retaintion Rate]),",
              "    BLANK(),",
              "[New Customer] - [Cohort Performance])"
            ],
            "formatString": "0",
            "lineageTag": "0a56d6b7-991f-4a8c-aca6-33614cf49887"
          },
          {
            "name": "Churned rate",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "DIVIDE([Churned Customer], [New Customer])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "87f0d7c5-6f59-40be-8a50-f8799b40443f"
          },
          {
            "name": "Recovered Customers",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "VAR _Customers_This_Month = ",
              "    VALUES(Fact_Sales[Customer ID])",
              "",
              "VAR _Customer_last_month = ",
              "    CALCULATETABLE(",
              "        VALUES(Fact_Sales[Customer ID]),",
              "        PREVIOUSMONTH(DimDate[Start of Month])",
              "    )",
              "",
              "VAR _New_customer = ",
              "    CALCULATETABLE(",
              "        VALUES(Fact_Sales[Customer ID]),",
              "        Fact_Sales[Month Since First Transation] = 0",
              "    )",
              "",
              "VAR _Recovered_Customers = ",
              "    EXCEPT(EXCEPT(_Customers_This_Month,_Customer_last_month), _New_customer)",
              "",
              "RETURN",
              "    COUNTROWS(_Recovered_Customers)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0971661d-3507-44e0-b5ad-663496428d81"
          },
          {
            "name": "Lost_customer",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "",
              "VAR _Customers_This_Month = ",
              "    VALUES(Fact_Sales[Customer ID])",
              "",
              "VAR _Customer_last_month = ",
              "    CALCULATETABLE(",
              "        VALUES(Fact_Sales[Customer ID]),",
              "        PREVIOUSMONTH(DimDate[Start of Month])",
              "    )",
              "",
              "VAR _Lost_Customer =",
              "    EXCEPT(_Customer_last_month, _Customers_This_Month)",
              "",
              "RETURN",
              "    COUNTROWS(_Lost_Customer)"
            ],
            "formatString": "0",
            "lineageTag": "c24e6a5f-85c2-4f45-9ccd-b17e29f7057d"
          }
        ],
        "partitions": [
          {
            "name": "_Measure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9192bebc00aa46c0acd00adfaa5b8806"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "9922c743-7d48-437f-ba3d-fecb79f3d14e",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "596ef2f6-4772-43fb-965d-e79c2f1912f0",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "978150ab-55ce-4412-bb66-4d0f5eea661a",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "57e96fc2-7bca-4354-a5ce-85d5a49831e9",
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Cohort Performance\", NAMEOF('_Measure'[Cohort Performance]), 0),",
                "    (\"Churned Customer\", NAMEOF('_Measure'[Churned Customer]), 1),",
                "    (\"Churned rate\", NAMEOF('_Measure'[Churned rate]), 2),",
                "    (\"Retaintion Rate\", NAMEOF('_Measure'[Retaintion Rate]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}