{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.137.751.0 (24.10)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Fact_Sales\",\"Clean_Data_Function\",\"Dim_Customer\",\"StartDate\",\"EndDate\",\"DimDate\",\"_Measure\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "dim_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dim customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Dim_Customer": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "dim client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "dim consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "dim user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "dim buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "dim patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "dim purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "dim shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "dim_customer.customer_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Customer",
                    "ConceptualProperty": "Customer ID"
                  }
                },
                "NameType": "Identifier",
                "State": "Generated",
                "Terms": [
                  {
                    "customer ID": {
                      "State": "Generated"
                    }
                  },
                  {
                    "ID": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "dim_customer.first_transation_month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Dim_Customer",
                    "ConceptualProperty": "First_transation_month"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "first transation month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "First_transation_month": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "first transation mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  }
                ]
              },
              "dim_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "dim date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "DimDate": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "dim moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "dim period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "dim_date.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Date"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "dim_date.start_of_month": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "DimDate",
                    "ConceptualProperty": "Start of Month"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "start of month": {
                      "State": "Generated"
                    }
                  },
                  {
                    "start": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "start of mth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "twitch of month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "jump of month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "jerk of month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "flinch of month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "jolt of month": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "twitch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "jump": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "jerk": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "flinch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "Cohort": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "fact_sale": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Sales"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "fact sale": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Fact_Sales": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "sale": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "fact auction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "auction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fact transaction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "transaction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "fact deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "fact trade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "fact vending": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "fact retailing": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "fact selling": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "deal": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "fact_sale.country": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Sales",
                    "ConceptualProperty": "Country"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "country": {
                      "State": "Generated"
                    }
                  },
                  {
                    "nation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "location": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "fact_sale.customer_ID": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Sales",
                    "ConceptualProperty": "Customer ID"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "customer ID": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "customer identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "customer identifier": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "fact_sale.invoice": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Sales",
                    "ConceptualProperty": "Invoice"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "invoice": {
                      "State": "Generated"
                    }
                  },
                  {
                    "statement": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "demand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "account": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "fact_sale.invoice_date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Sales",
                    "ConceptualProperty": "InvoiceDate"
                  }
                },
                "SemanticType": "Time",
                "State": "Generated",
                "Terms": [
                  {
                    "invoice date": {
                      "State": "Generated"
                    }
                  },
                  {
                    "InvoiceDate": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "date": {
                      "State": "Generated",
                      "Weight": 0.7
                    }
                  },
                  {
                    "invoice moment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "invoice period": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "fact_sale.month_since_first_transation": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Sales",
                    "ConceptualProperty": "Month Since First Transation"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "month since first transation": {
                      "State": "Generated"
                    }
                  },
                  {
                    "mth since first transation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.771
                    }
                  }
                ]
              },
              "fact_sale.name": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Sales",
                    "ConceptualProperty": "Name"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "title": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "label": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "tag": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "fact_sale.price": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Sales",
                    "ConceptualProperty": "Price"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "price": {
                      "State": "Generated"
                    }
                  },
                  {
                    "worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "fee": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "bill": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "expense": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "outlay": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "penalty": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "punishment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "fine": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.452
                    }
                  }
                ]
              },
              "fact_sale.quantity": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Fact_Sales",
                    "ConceptualProperty": "Quantity"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "quantity": {
                      "State": "Generated"
                    }
                  },
                  {
                    "extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "magnitude": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "measure": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "size": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "capacity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "mass": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "parameter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Parameter"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "parameter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "stricture": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "limitation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "restriction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "constraint": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "consideration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "boundary": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "limit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "bound": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "factor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "issue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "parameter.parameter": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Parameter",
                    "ConceptualProperty": "Parameter"
                  }
                },
                "NameType": "Name",
                "State": "Generated",
                "Terms": [
                  {
                    "parameter": {
                      "State": "Generated"
                    }
                  },
                  {
                    "parameter name": {
                      "State": "Generated"
                    }
                  },
                  {
                    "stricture": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "limitation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "restriction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "constraint": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "consideration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "boundary": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "limit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "bound": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "factor": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "issue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ]
              },
              "parameter.parameter_field": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Parameter",
                    "ConceptualProperty": "Parameter Fields"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "parameter field": {
                      "State": "Generated"
                    }
                  },
                  {
                    "field": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "parameter arena": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "arena": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "parameter turf": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter ground": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter pitch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter park": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "turf": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "ground": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "pitch": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "park": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "parameter.parameter_order": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Parameter",
                    "ConceptualProperty": "Parameter Order"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "parameter order": {
                      "State": "Generated"
                    }
                  },
                  {
                    "order": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "parameter instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "parameter direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "parameter edict": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "edict": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "parameter command": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter directive": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter demand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "parameter mandate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              },
              "v_Measure_measure": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "_measure": {
                      "State": "Generated"
                    }
                  },
                  {
                    "_ degree": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "_ quantity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "_ quota": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "_ extent": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "_ amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "_ portion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "_ ration": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "_ size": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "v_Measure_measure.PM_order": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "PM Order"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "PM order": {
                      "State": "Generated"
                    }
                  },
                  {
                    "order": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "pm instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "pm direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "pm edict": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "edict": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "pm command": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "pm directive": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "pm demand": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "pm mandate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "v_Measure_measure.PM_revenue": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "PM Revenue"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "PM revenue": {
                      "State": "Generated"
                    }
                  },
                  {
                    "revenue": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "pm income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "pm profit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "pm turnover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "pm yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "profit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "turnover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "v_Measure_measure.active_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Active Customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "active customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "active client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "active consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "active user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "active buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "active patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "active purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "active shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "v_Measure_measure.average_order_value": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Average Order Value"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "average order value": {
                      "State": "Generated"
                    }
                  },
                  {
                    "value": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "order value": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "average order assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.508
                    }
                  },
                  {
                    "order assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "average order worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "average order price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "average order cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "average order charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "average order rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.492
                    }
                  },
                  {
                    "assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "order worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "order price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "v_Measure_measure.average_revenue": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Average Revenue"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "average revenue": {
                      "State": "Generated"
                    }
                  },
                  {
                    "revenue": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "average income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "average profit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "average turnover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "average yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "profit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "turnover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "v_Measure_measure.churned_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Churned Customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "churned customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churned client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "churned consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "churned user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "churned buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "churned patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "churned purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "churned shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "v_Measure_measure.churned_rate": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Churned rate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "churned rate": {
                      "State": "Generated"
                    }
                  },
                  {
                    "rate": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "churned degree": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "churned frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "churned percentage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "churned ratio": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "churned quotient": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "degree": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "ratio": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "quotient": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "churned amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "v_Measure_measure.cohort_performance": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Cohort Performance"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "cohort performance": {
                      "State": "Generated"
                    }
                  },
                  {
                    "performance": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "cohort presentation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "cohort recital": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "cohort enactment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "presentation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "recital": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "enactment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "cohort act": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "cohort routine": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "cohort concert": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "cohort show": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "v_Measure_measure.lost_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Lost_customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "lost customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Lost_customer": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "lost client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "lost consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "lost user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "lost buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "lost patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "lost purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "lost shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "v_Measure_measure.new_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "New Customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "new customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "new client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "new shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "v_Measure_measure.recovered_customers": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Recovered Customers"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "recovered customers": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customers": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "recovered clientele": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "recovered patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "recovered client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "recovered consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "recovered punter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "clientele": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "punter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  }
                ]
              },
              "v_Measure_measure.retaind_customers": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Retaind Customers"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "retaind customers": {
                      "State": "Generated"
                    }
                  },
                  {
                    "retaind clientele": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaind patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaind client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaind consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaind punter": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaind regular": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "retaind custom": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "retaind trade": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "retaind business": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "retaind following": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "v_Measure_measure.retaintion_rate": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Retaintion Rate"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "retaintion rate": {
                      "State": "Generated"
                    }
                  },
                  {
                    "retaintion degree": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaintion frequency": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaintion percentage": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaintion ratio": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaintion quotient": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "retaintion amount": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "retaintion proportion": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "retaintion speed": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "retaintion level": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "retaintion scale": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "v_Measure_measure.total_customer": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Total Customer"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total customer": {
                      "State": "Generated"
                    }
                  },
                  {
                    "customer": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "total client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "total consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "total user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "total buyer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "total patron": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "total purchaser": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "total shopper": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "client": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "consumer": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "user": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  }
                ]
              },
              "v_Measure_measure.total_orders": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Total Orders"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total orders": {
                      "State": "Generated"
                    }
                  },
                  {
                    "orders": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "aggregate order": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall order": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "total instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total guideline": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total preparation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "total direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.5
                    }
                  },
                  {
                    "instruction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "guideline": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "preparation": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "direction": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  }
                ]
              },
              "v_Measure_measure.total_revenue": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Total Revenue"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total revenue": {
                      "State": "Generated"
                    }
                  },
                  {
                    "revenue": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "total income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.75
                    }
                  },
                  {
                    "income": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "total profit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "total turnover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "total yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "profit": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "turnover": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "yield": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  },
                  {
                    "aggregate revenue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall revenue": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "v_Measure_measure.total_unit_sold": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "_Measure",
                    "ConceptualProperty": "Total Unit Sold"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total unit sold": {
                      "State": "Generated"
                    }
                  },
                  {
                    "total module sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "total element sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "total entity sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.762
                    }
                  },
                  {
                    "total group sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total component sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total constituent sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total item sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total part sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "total section sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.739
                    }
                  },
                  {
                    "aggregate unit sold": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  }
                ]
              }
            },
            "Language": "en-US",
            "Relationships": {
              "dim_customer_has_first_transation_month": {
                "Binding": {
                  "ConceptualEntity": "Dim_Customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_customer.first_transation_month"
                      },
                      "Subject": {
                        "Role": "dim_customer"
                      }
                    },
                    "ID": "dim_customers_have_first_transation_months",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_customer": {
                    "Target": {
                      "Entity": "dim_customer"
                    }
                  },
                  "dim_customer.first_transation_month": {
                    "Target": {
                      "Entity": "dim_customer.first_transation_month"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_customer_has_v_Measure_measure_average_revenue": {
                "Binding": {
                  "ConceptualEntity": "Dim_Customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.average_revenue"
                      },
                      "Subject": {
                        "Role": "dim_customer"
                      }
                    },
                    "ID": "dim_customers_have_average_revenue",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_customer": {
                    "Target": {
                      "Entity": "dim_customer"
                    }
                  },
                  "v_Measure_measure.average_revenue": {
                    "Target": {
                      "Entity": "v_Measure_measure.average_revenue"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_customer_has_v_Measure_measure_total_customer": {
                "Binding": {
                  "ConceptualEntity": "Dim_Customer"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.total_customer"
                      },
                      "Subject": {
                        "Role": "dim_customer"
                      }
                    },
                    "ID": "dim_customers_have_total_customer",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_customer": {
                    "Target": {
                      "Entity": "dim_customer"
                    }
                  },
                  "v_Measure_measure.total_customer": {
                    "Target": {
                      "Entity": "v_Measure_measure.total_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_customer_is_named_customer_ID": {
                "Binding": {
                  "ConceptualEntity": "Dim_Customer"
                },
                "Phrasings": [
                  {
                    "ID": "customer_ID_are_names_IDs_of_dim_customers",
                    "Name": {
                      "Name": {
                        "Role": "dim_customer.customer_ID"
                      },
                      "Subject": {
                        "Role": "dim_customer"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_customer.customer_ID"
                      },
                      "Subject": {
                        "Role": "dim_customer"
                      }
                    },
                    "ID": "dim_customers_have_customer_ID",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_customer": {
                    "Target": {
                      "Entity": "dim_customer"
                    }
                  },
                  "dim_customer.customer_ID": {
                    "Target": {
                      "Entity": "dim_customer.customer_ID"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_date": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.date"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.date": {
                    "Target": {
                      "Entity": "dim_date.date"
                    }
                  }
                },
                "State": "Generated"
              },
              "dim_date_has_start_of_month": {
                "Binding": {
                  "ConceptualEntity": "DimDate"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date.start_of_month"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_start_of_month",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "dim_date.start_of_month": {
                    "Target": {
                      "Entity": "dim_date.start_of_month"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_country": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sale.country"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_countries",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "fact_sale.country": {
                    "Target": {
                      "Entity": "fact_sale.country"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_dim_customer": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_customer"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_dim_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sale"
                      },
                      "Subject": {
                        "Role": "dim_customer"
                      }
                    },
                    "ID": "dim_customers_have_fact_sales",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_customer": {
                    "Target": {
                      "Entity": "dim_customer"
                    }
                  },
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_dim_date": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "dim_date"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_dim_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sale"
                      },
                      "Subject": {
                        "Role": "dim_date"
                      }
                    },
                    "ID": "dim_dates_have_fact_sales",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "dim_date": {
                    "Target": {
                      "Entity": "dim_date"
                    }
                  },
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_invoice": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sale.invoice"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_invoices",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "fact_sale.invoice": {
                    "Target": {
                      "Entity": "fact_sale.invoice"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_invoice_date": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sale.invoice_date"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_invoice_dates",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "fact_sale.invoice_date": {
                    "Target": {
                      "Entity": "fact_sale.invoice_date"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_month_since_first_transation": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sale.month_since_first_transation"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_month_since_first_transation",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "fact_sale.month_since_first_transation": {
                    "Target": {
                      "Entity": "fact_sale.month_since_first_transation"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_name": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sale.name"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_names",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "fact_sale.name": {
                    "Target": {
                      "Entity": "fact_sale.name"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_quantity": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sale.quantity"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_quantities",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "fact_sale.quantity": {
                    "Target": {
                      "Entity": "fact_sale.quantity"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_PM_order": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.PM_order"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_PM_order",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.PM_order": {
                    "Target": {
                      "Entity": "v_Measure_measure.PM_order"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_PM_revenue": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.PM_revenue"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_PM_revenue",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.PM_revenue": {
                    "Target": {
                      "Entity": "v_Measure_measure.PM_revenue"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_active_customer": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.active_customer"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_active_customer",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.active_customer": {
                    "Target": {
                      "Entity": "v_Measure_measure.active_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_average_order_value": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.average_order_value"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_average_order_value",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.average_order_value": {
                    "Target": {
                      "Entity": "v_Measure_measure.average_order_value"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_average_revenue": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.average_revenue"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_average_revenue",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.average_revenue": {
                    "Target": {
                      "Entity": "v_Measure_measure.average_revenue"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_churned_customer": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.churned_customer"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_churned_customer",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.churned_customer": {
                    "Target": {
                      "Entity": "v_Measure_measure.churned_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_churned_rate": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.churned_rate"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_churned_rate",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.churned_rate": {
                    "Target": {
                      "Entity": "v_Measure_measure.churned_rate"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_cohort_performance": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.cohort_performance"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_cohort_performance",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.cohort_performance": {
                    "Target": {
                      "Entity": "v_Measure_measure.cohort_performance"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_lost_customer": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.lost_customer"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_lost_customer",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.lost_customer": {
                    "Target": {
                      "Entity": "v_Measure_measure.lost_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_new_customer": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.new_customer"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_new_customer",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.new_customer": {
                    "Target": {
                      "Entity": "v_Measure_measure.new_customer"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_recovered_customers": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.recovered_customers"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_recovered_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.recovered_customers": {
                    "Target": {
                      "Entity": "v_Measure_measure.recovered_customers"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_retaind_customers": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.retaind_customers"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_retaind_customers",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.retaind_customers": {
                    "Target": {
                      "Entity": "v_Measure_measure.retaind_customers"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_retaintion_rate": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.retaintion_rate"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_retaintion_rate",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.retaintion_rate": {
                    "Target": {
                      "Entity": "v_Measure_measure.retaintion_rate"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_total_orders": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.total_orders"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_total_orders",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.total_orders": {
                    "Target": {
                      "Entity": "v_Measure_measure.total_orders"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_total_revenue": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.total_revenue"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_total_revenue",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.total_revenue": {
                    "Target": {
                      "Entity": "v_Measure_measure.total_revenue"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_has_v_Measure_measure_total_unit_sold": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "v_Measure_measure.total_unit_sold"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_total_unit_sold",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "v_Measure_measure.total_unit_sold": {
                    "Target": {
                      "Entity": "v_Measure_measure.total_unit_sold"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_in_country": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "ID": "fact_sales_are_in_countries",
                    "Preposition": {
                      "Object": {
                        "Role": "fact_sale.country"
                      },
                      "Prepositions": [
                        {
                          "in": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "fact_sale.country": {
                    "Target": {
                      "Entity": "fact_sale.country"
                    }
                  }
                },
                "SemanticSlots": {
                  "Where": {
                    "Role": "fact_sale.country"
                  }
                },
                "State": "Generated"
              },
              "fact_sale_is_expensive": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "fact_sale.price"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "price_indicates_how_expensive_fact_sales_are",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "fact_sale.price"
                      },
                      "Subject": {
                        "Role": "fact_sale"
                      }
                    },
                    "ID": "fact_sales_have_prices",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "fact_sale.price": {
                    "Target": {
                      "Entity": "fact_sale.price"
                    }
                  }
                },
                "State": "Generated"
              },
              "fact_sale_is_invoiced_on_invoice_date": {
                "Binding": {
                  "ConceptualEntity": "Fact_Sales"
                },
                "Phrasings": [
                  {
                    "ID": "fact_sales_are_invoiced_on_invoice_dates",
                    "State": "Generated",
                    "Verb": {
                      "Object": {
                        "Role": "fact_sale"
                      },
                      "Verbs": [
                        {
                          "invoice": {
                            "State": "Generated"
                          }
                        }
                      ]
                    },
                    "Weight": 0.9
                  }
                ],
                "Roles": {
                  "fact_sale": {
                    "Target": {
                      "Entity": "fact_sale"
                    }
                  },
                  "fact_sale.invoice_date": {
                    "Target": {
                      "Entity": "fact_sale.invoice_date"
                    }
                  }
                },
                "SemanticSlots": {
                  "When": {
                    "Role": "fact_sale.invoice_date"
                  }
                },
                "State": "Generated"
              },
              "parameter_is_named_parameter": {
                "Binding": {
                  "ConceptualEntity": "Parameter"
                },
                "Phrasings": [
                  {
                    "ID": "parameters_are_names_IDs_of_parameters",
                    "Name": {
                      "Name": {
                        "Role": "parameter.parameter"
                      },
                      "Subject": {
                        "Role": "parameter"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "parameter.parameter"
                      },
                      "Subject": {
                        "Role": "parameter"
                      }
                    },
                    "ID": "parameters_have_parameters",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "parameter": {
                    "Target": {
                      "Entity": "parameter"
                    }
                  },
                  "parameter.parameter": {
                    "Target": {
                      "Entity": "parameter.parameter"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Clean_Data_Function",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "(DataSheet as table) =>",
          "let",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(DataSheet, [PromoteAllScalars=true]),",
          "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Promoted Headers\",{{\"Invoice\", type any}, {\"StockCode\", type any}, {\"Description\", type text}, {\"Quantity\", Int64.Type}, {\"InvoiceDate\", type datetime}, {\"Price\", type number}, {\"Customer ID\", Int64.Type}, {\"Country\", type text}}),",
          "    #\"Filtered Rows\" = Table.SelectRows(#\"Changed Type\", each ([Customer ID] <> null and [Customer ID] <> \"\")),",
          "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"StockCode\", \"Description\"}),",
          "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Removed Columns\",{{\"Invoice\", type text}}),",
          "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type1\", each not Text.StartsWith([Invoice], \"C\")),",
          "    #\"Filtered Rows2\" = Table.SelectRows(#\"Filtered Rows1\", each [Price] > 0),",
          "    #\"Reordered Columns\" = Table.ReorderColumns(#\"Filtered Rows2\",{\"Invoice\", \"InvoiceDate\", \"Customer ID\", \"Country\", \"Quantity\", \"Price\"})",
          "in",
          "    #\"Reordered Columns\""
        ],
        "kind": "m",
        "lineageTag": "da2c3d4c-650d-41d5-8e7d-725fab63a2e4"
      },
      {
        "name": "StartDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2009, 12, 1)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "067827fe-59df-44b7-b82a-39addf8f231d"
      },
      {
        "name": "EndDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Date"
          }
        ],
        "expression": [
          "let",
          "    Source = #date(2011, 12, 1)",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "b20e5a7e-7f49-484d-97e3-6afcccabd114"
      }
    ],
    "relationships": [
      {
        "name": "AutoDetected_10403d2c-a23e-4554-ae70-bb055c739657",
        "fromColumn": "Customer ID",
        "fromTable": "Fact_Sales",
        "toColumn": "Customer ID",
        "toTable": "Dim_Customer"
      },
      {
        "name": "5e2ae74c-a7d5-e821-21a2-d8fc9be37f90",
        "fromColumn": "InvoiceDate",
        "fromTable": "Fact_Sales",
        "toColumn": "Date",
        "toTable": "DimDate"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Fact_Sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Invoice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86577d39-6b6d-4331-857e-c81b137de7a6",
            "sourceColumn": "Invoice",
            "summarizeBy": "none"
          },
          {
            "name": "Quantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "80224408-7b3b-4b44-80a4-51b7eca4a341",
            "sourceColumn": "Quantity",
            "summarizeBy": "sum"
          },
          {
            "name": "InvoiceDate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "1c63196d-effd-4062-b786-662da7799c33",
            "sourceColumn": "InvoiceDate",
            "summarizeBy": "none"
          },
          {
            "name": "Price",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "decimal",
            "lineageTag": "dee25a75-d43b-4f08-bbc1-a4214f6262d5",
            "sourceColumn": "Price",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "137fae89-9733-4e05-9126-371237d630a2",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "309c9356-f66d-42b2-bd2b-3e5d0c0a1467",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ff873f9d-0b8c-4c39-b3b3-1180389eb483",
            "sourceColumn": "Name",
            "summarizeBy": "none"
          },
          {
            "name": "Month Since First Transation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "    DATEDIFF(",
              "        RELATED(Dim_Customer[First_transation_month]),",
              "        RELATED(DimDate[Date]),",
              "        MONTH",
              "    )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "24c6335c-9b6c-4767-b584-58c2c355c0e8",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "cf195353-8c47-48ce-9e85-820478ce5ede",
        "partitions": [
          {
            "name": "Fact_Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(\"H:\\_Portfolio Project Github\\Chohort Analysis\\online_retail_II.xlsx\"), null, true),",
                "    #\"Filtered Rows\" = Table.SelectRows(Source, each ([Kind] = \"Sheet\")),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Filtered Rows\",{\"Item\", \"Kind\", \"Hidden\"}),",
                "    #\"Invoked Custom Function\" = Table.AddColumn(#\"Removed Columns\", \"Clean_Data\", each Clean_Data_Function([Data])),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Invoked Custom Function\",{\"Data\"}),",
                "    #\"Expanded Clean_Data\" = Table.ExpandTableColumn(#\"Removed Columns1\", \"Clean_Data\", {\"Invoice\", \"InvoiceDate\", \"Customer ID\", \"Country\", \"Quantity\", \"Price\"}, {\"Invoice\", \"InvoiceDate\", \"Customer ID\", \"Country\", \"Quantity\", \"Price\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Clean_Data\",{{\"InvoiceDate\", type date}}),",
                "    #\"Filtered Rows1\" = Table.SelectRows(#\"Changed Type\", each true),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Filtered Rows1\",{{\"Quantity\", Int64.Type}, {\"Price\", Currency.Type}, {\"Customer ID\", Int64.Type}, {\"Invoice\", type text}}),",
                "    #\"Filtered Rows2\" = Table.SelectRows(#\"Changed Type1\", each true)",
                "in",
                "    #\"Filtered Rows2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Dim_Customer",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Customer ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fa86e4ac-7b92-4a05-9349-05e5aefdfe28",
            "sourceColumn": "Customer ID",
            "summarizeBy": "none"
          },
          {
            "name": "First_transation_month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "846bfa7d-a4e6-4bf2-85ad-fed120b4f346",
            "sourceColumn": "First_transation_month",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "0c0424eb-3cd8-493a-9b5a-f0f8063cf424",
        "partitions": [
          {
            "name": "Dim_Customer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Fact_Sales,",
                "    #\"Grouped Rows\" = Table.Group(Source, {\"Customer ID\"}, {{\"First_transation_month\", each List.Min([InvoiceDate]), type nullable date}}),",
                "    #\"Calculated Start of Month\" = Table.TransformColumns(#\"Grouped Rows\",{{\"First_transation_month\", Date.StartOfMonth, type date}})",
                "in",
                "    #\"Calculated Start of Month\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DimDate",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Short Date",
            "lineageTag": "15c03722-02a5-4377-ad9b-315d45bd918f",
            "sourceColumn": "Date",
            "summarizeBy": "none"
          },
          {
            "name": "Start of Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ],
            "dataType": "dateTime",
            "formatString": "mmmm d\\, yyyy",
            "lineageTag": "fcdecbb5-4cfd-487b-bf3f-b2bd49eae75d",
            "sourceColumn": "Start of Month",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9c4200b0-3e2e-4451-b8f0-a4b93fac6d60",
        "partitions": [
          {
            "name": "DimDate",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = {Number.From(StartDate)..Number.From(EndDate)},",
                "    #\"Converted to Table\" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Converted to Table\",{{\"Column1\", type date}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"Column1\", \"Date\"}}),",
                "    #\"Inserted Start of Month\" = Table.AddColumn(#\"Renamed Columns\", \"Start of Month\", each Date.StartOfMonth([Date]), type date)",
                "in",
                "    #\"Inserted Start of Month\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "_Measure",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "lineageTag": "841983c5-1ba6-4120-baf5-473c445cb668",
        "measures": [
          {
            "name": "Total Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Regular Measure",
            "expression": "SUMX(Fact_Sales, Fact_Sales[Quantity]*Fact_Sales[Price])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "8e3bb74a-42c5-4467-85ea-0ca96c4289a7"
          },
          {
            "name": "Total Orders",
            "displayFolder": "Regular Measure",
            "expression": "DISTINCTCOUNT(Fact_Sales[Invoice])",
            "formatString": "0",
            "lineageTag": "2208aefe-bc4c-4c51-9e1d-bdd54d7002e3"
          },
          {
            "name": "Total Unit Sold",
            "displayFolder": "Regular Measure",
            "expression": "SUM(Fact_Sales[Quantity])",
            "formatString": "0",
            "lineageTag": "c9d02731-3e2a-4b6e-b772-1576e6f736de"
          },
          {
            "name": "Total Customer",
            "displayFolder": "Regular Measure",
            "expression": "COUNTROWS(Dim_Customer)",
            "formatString": "0",
            "lineageTag": "bdfb47a3-89ed-4372-b1a7-2830458ef6f0"
          },
          {
            "name": "Average Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Regular Measure",
            "expression": "DIVIDE([Total Revenue], [Total Customer])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "8f956741-43d7-43e5-8ded-97aac5a146a1"
          },
          {
            "name": "Average Order Value",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Regular Measure",
            "expression": "DIVIDE([Total Revenue], [Total Orders])",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "57221760-81be-46be-88d8-e9bad8b321dd"
          },
          {
            "name": "PM Revenue",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ],
            "displayFolder": "Regular Measure",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Revenue],",
              "    DATEADD(DimDate[Date], -1, MONTH)",
              ")"
            ],
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "lineageTag": "ac9dd75a-18ad-411e-b489-69e178f763f5"
          },
          {
            "name": "PM Order",
            "displayFolder": "Regular Measure",
            "expression": [
              "",
              "CALCULATE(",
              "    [Total Orders],",
              "    DATEADD(DimDate[Date], -1, MONTH)",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "64647cca-e5f3-400a-bf69-070f7ab6dbd2"
          },
          {
            "name": "Active Customer",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "COUNTROWS(VALUES(Fact_Sales[Customer ID]))"
            ],
            "formatString": "0",
            "lineageTag": "8f1e396d-eb36-431e-8bbb-17407e8affc1"
          },
          {
            "name": "New Customer",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "CALCULATE(",
              "    [Active Customer],",
              "    Fact_Sales[Month Since First Transation]=0)"
            ],
            "formatString": "0",
            "lineageTag": "8e4e5f93-55cc-4c14-a3ca-b3b8582a1e17"
          },
          {
            "name": "Cohort Performance",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "",
              "VAR _minDate = MIN(DimDate[Start of Month])",
              "",
              "VAR _maxDate = MAX(DimDate[Start of Month])",
              "",
              "RETURN",
              "    CALCULATE(",
              "        [Active Customer],",
              "        REMOVEFILTERS(DimDate[Start of Month]),",
              "        RELATEDTABLE(Dim_Customer),",
              "        Dim_Customer[First_transation_month]>= _minDate",
              "            && Dim_Customer[First_transation_month]<= _maxDate",
              "    )"
            ],
            "formatString": "0",
            "lineageTag": "bcf8df61-8e0a-46db-83dc-97a97cfcf7fb"
          },
          {
            "name": "Retaind Customers",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "VAR _ThisMonth=VALUES(Fact_Sales[Customer ID])",
              "VAR _LastMonth = CALCULATETABLE(",
              "    VALUES(Fact_Sales[Customer ID]),",
              "    PREVIOUSMONTH(DimDate[Start of Month])",
              ")",
              "VAR _RetaindCustomer = ",
              "    INTERSECT(_ThisMonth, _LastMonth)",
              "RETURN",
              "COUNTROWS(_RetaindCustomer)"
            ],
            "formatString": "0",
            "lineageTag": "9af8baa1-fc0a-46c4-9a28-3636042495a7"
          },
          {
            "name": "Retaintion Rate",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "DIVIDE([Cohort Performance], [New Customer])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dc4c3b31-190e-475c-b5ae-e799e901a826"
          },
          {
            "name": "Churned Customer",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              " SWITCH(",
              "    TRUE(),",
              "    ISBLANK([Retaintion Rate]),",
              "    BLANK(),",
              "[New Customer] - [Cohort Performance])"
            ],
            "formatString": "0",
            "lineageTag": "0a56d6b7-991f-4a8c-aca6-33614cf49887"
          },
          {
            "name": "Churned rate",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "DIVIDE([Churned Customer], [New Customer])"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "87f0d7c5-6f59-40be-8a50-f8799b40443f"
          },
          {
            "name": "Recovered Customers",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "VAR _Customers_This_Month = ",
              "    VALUES(Fact_Sales[Customer ID])",
              "",
              "VAR _Customer_last_month = ",
              "    CALCULATETABLE(",
              "        VALUES(Fact_Sales[Customer ID]),",
              "        PREVIOUSMONTH(DimDate[Start of Month])",
              "    )",
              "",
              "VAR _New_customer = ",
              "    CALCULATETABLE(",
              "        VALUES(Fact_Sales[Customer ID]),",
              "        Fact_Sales[Month Since First Transation] = 0",
              "    )",
              "",
              "VAR _Recovered_Customers = ",
              "    EXCEPT(EXCEPT(_Customers_This_Month,_Customer_last_month), _New_customer)",
              "",
              "RETURN",
              "    COUNTROWS(_Recovered_Customers)",
              ""
            ],
            "formatString": "0",
            "lineageTag": "0971661d-3507-44e0-b5ad-663496428d81"
          },
          {
            "name": "Lost_customer",
            "displayFolder": "Cohort Measure",
            "expression": [
              "",
              "",
              "VAR _Customers_This_Month = ",
              "    VALUES(Fact_Sales[Customer ID])",
              "",
              "VAR _Customer_last_month = ",
              "    CALCULATETABLE(",
              "        VALUES(Fact_Sales[Customer ID]),",
              "        PREVIOUSMONTH(DimDate[Start of Month])",
              "    )",
              "",
              "VAR _Lost_Customer =",
              "    EXCEPT(_Customer_last_month, _Customers_This_Month)",
              "",
              "RETURN",
              "    COUNTROWS(_Lost_Customer)"
            ],
            "formatString": "0",
            "lineageTag": "c24e6a5f-85c2-4f45-9ccd-b17e29f7057d"
          }
        ],
        "partitions": [
          {
            "name": "_Measure",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"Column1\", type text}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type\",{\"Column1\"})",
                "in",
                "    #\"Removed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "Parameter",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "9192bebc00aa46c0acd00adfaa5b8806"
          }
        ],
        "columns": [
          {
            "name": "Parameter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": false,
            "lineageTag": "9922c743-7d48-437f-ba3d-fecb79f3d14e",
            "relatedColumnDetails": {
              "groupByColumns": [
                {
                  "groupingColumn": "Parameter Fields"
                }
              ]
            },
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value1]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Fields",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "extendedProperties": [
              {
                "name": "ParameterMetadata",
                "type": "json",
                "value": {
                  "kind": 2,
                  "version": 3
                }
              }
            ],
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "596ef2f6-4772-43fb-965d-e79c2f1912f0",
            "sortByColumn": "Parameter Order",
            "sourceColumn": "[Value2]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Parameter Order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": false,
            "lineageTag": "978150ab-55ce-4412-bb66-4d0f5eea661a",
            "sourceColumn": "[Value3]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "57e96fc2-7bca-4354-a5ce-85d5a49831e9",
        "partitions": [
          {
            "name": "Parameter",
            "mode": "import",
            "source": {
              "expression": [
                "{",
                "    (\"Cohort Performance\", NAMEOF('_Measure'[Cohort Performance]), 0),",
                "    (\"Churned Customer\", NAMEOF('_Measure'[Churned Customer]), 1),",
                "    (\"Churned rate\", NAMEOF('_Measure'[Churned rate]), 2),",
                "    (\"Retaintion Rate\", NAMEOF('_Measure'[Retaintion Rate]), 3)",
                "}"
              ],
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}